// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/unit2022-bosch/teapot/backend/internal/app/orm"
	"github.com/unit2022-bosch/teapot/backend/internal/app/webserver"
	"github.com/unit2022-bosch/teapot/backend/internal/services/auth"
)

// Injectors from wire.go:

func BuildWebServer() (*webserver.App, error) {
	webConfig, err := webserver.NewWebConfig()
	if err != nil {
		return nil, err
	}
	dbConfig, err := orm.NewDbConfig()
	if err != nil {
		return nil, err
	}
	db, err := orm.NewDB(dbConfig)
	if err != nil {
		return nil, err
	}
	iAuthRepository := auth.NewAuthGormRepository(db)
	authConfig := auth.NewAuthConfig()
	iAuthService := auth.NewAuthService(iAuthRepository, authConfig)
	authRestController := auth.NewAuthRestController(iAuthService)
	router := webserver.NewRouter(authRestController)
	iAuthDbSeeder := auth.NewAuthDbSeeder(iAuthService)
	migrator := orm.NewMigrator(db, iAuthDbSeeder)
	app := webserver.NewApp(webConfig, router, migrator)
	return app, nil
}
